
main:
	g++ -o main main.cpp -std=c++11 \
		-I/home/daiver/R3DS/3rdparty/eigen-3.2.4/build123/include/eigen3 \
		-I/home/daiver/coding/libs/ViennaCL-1.7.1/ \
		-L/home/daiver/coding/libs/ViennaCL-1.7.1/build/libviennacl/libviennacl.so \
		-lOpenCL \
		-O3 \
		-Wno-ignored-attributes


