gen_ann:
	ghc -O2 --make gen_ann.hs -o gen_ann -threaded -rtsopts 2>&1

pars4:
	ghc -O2 --make pars4.hs -o pars4 -threaded -rtsopts 2>&1

pars2:
	ghc -O2 --make pars2.hs -o pars2 -threaded -rtsopts 2>&1

cn:
	ghc -O2 --make cn.hs -o cn -threaded -rtsopts 2>&1

rsa_1:
	ghc -O2 --make rsa_1.hs -o rsa_1 -threaded -rtsopts 2>&1

rand_coins:
	ghc -O2 --make rand_coins.hs -o rand_coins -threaded -rtsopts 2>&1

pass_brute:
	ghc -O2 --make pass_brute.hs -o pass_brute -threaded -rtsopts 2>&1

misc6:
	ghc -O2 --make misc6.hs -o misc6 -threaded -rtsopts 2>&1

lab3:
	ghc -O2 --make lab3.hs -o lab3 -threaded -rtsopts 2>&1

spamtest3:
	ghc -O2 --make spamtest3.hs -o spamtest3 -threaded -rtsopts 2>&1

misc5:
	ghc -O2 --make misc5.hs -o misc5 -threaded -rtsopts 2>&1

live:
	ghc -O2 --make live.hs -o live -threaded -rtsopts 2>&1

misc4:
	ghc -O2 --make misc4.hs -o misc4 -threaded -rtsopts 2>&1

lab2:
	ghc -O2 --make lab2.hs -o lab2 -threaded -rtsopts 2>&1

lab:
	ghc -O2 --make lab.hs -o lab -threaded -rtsopts 2>&1

misc3:
	ghc -O2 --make misc3.hs -o misc3 -threaded -rtsopts 2>&1

sct:
	ghc -O2 --make sct.hs -o sct -threaded -rtsopts 2>&1

googler:
	ghc -O2 --make googler.hs -o googler -threaded -rtsopts 2>&1

prefixtree1:
	ghc -O2 --make prefixtree1.hs -o prefixtree1 -threaded -rtsopts 2>&1

misc2:
	ghc -O2 --make misc2.hs -o misc2 -threaded -rtsopts 2>&1

weather:
	ghc -O2 --make weather.hs -o weather -threaded -rtsopts 2>&1

wdparser:
	ghc -O2 --make wdparser.hs -o wdparser -threaded -rtsopts 2>&1

misc:
	ghc -O2 --make misc.hs -o misc -threaded -rtsopts 2>&1
	
gen_alg:
	ghc -O2 --make gen_alg.hs -o gen_alg -threaded -rtsopts 2>&1

random_work:
	ghc -O2 --make random_work.hs -o random_work -threaded -rtsopts 2>&1

spamtest2:
	ghc -O2 --make spamtest2.hs -o spamtest2 -threaded -rtsopts 2>&1
