
rotationCOLnAdept:
	clang++-3.5 rotationCOLnAdept.cpp -ladept -o rotationCOLnAdept -std=c++11 -I/usr/local/include/eigen3/

#linregCppOptLib:
	#clang++-3.5 linregCppOptLib.cpp -ladept -o linregCppOptLib -std=c++11 -I/usr/local/include/eigen3/

#linregEigen:
	#clang++-3.5 linregEigen.cpp -ladept -o linregEigen -std=c++11

#linreg:
	#g++ linreg.cpp -ladept -o linreg -std=c++11

#main:
	#g++ main.cpp -ladept -o main
