Default: &defaults
  database: ytutor.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ytutor_test.sqlite3
  <<: *defaults

Staging:
  database: ytutor_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ytutor_production.sqlite3
  poolsize: 100
  <<: *defaults
