
main:
	g++ -o main main.cpp -std=c++11 \
		-I/usr/local/include/eigen3/ \
		-I/home/daiver/coding/libs/ViennaCL-1.7.1/ \
		-L/home/daiver/coding/libs/ViennaCL-1.7.1/build/libviennacl/libviennacl.so \
		-lOpenCL


